const cfg=window.LLDB_CONFIG||{};const $=(s)=>document.querySelector(s);const $$=(s)=>[...document.querySelectorAll(s)];
const sections=[['🏠','Inicio','inicio'],['👥','Conócenos','mision'],['📚','Recursos espirituales','recursos'],['🎙️','Sermones','sermones'],['📖','Estudios bíblicos','estudio'],['🙏','Peticiones','peticiones'],['❤️','Testimonios','testimonios'],['🎬','Media','media'],['💝','Donaciones','donaciones'],['✉️','Contacto','contacto'],['🤝','Afiliados','afiliados']];
$('#mainGrid').innerHTML=sections.map(([i,n,id])=>`<a class="nav-card" href="#${id}"><b>${i}</b><span>${n.toUpperCase()}</span></a>`).join('');$('#drawerNav').innerHTML=`<a href="#radio">📻 Radio</a>`+sections.map(([i,n,id])=>`<a href="#${id}">${i} ${n}</a>`).join('');
let audioCtx,rainNode,soundOn=false;function ambient(on){soundOn=on;[$('#soundToggle'),$('#soundToggleHeader')].forEach(b=>{if(b)b.setAttribute('aria-pressed',String(on))});if(on){audioCtx=audioCtx||new (window.AudioContext||window.webkitAudioContext)();if(audioCtx.state==='suspended')audioCtx.resume();const buffer=audioCtx.createBuffer(1,audioCtx.sampleRate*2,audioCtx.sampleRate);const d=buffer.getChannelData(0);for(let i=0;i<d.length;i++)d[i]=(Math.random()*2-1)*.18;rainNode=audioCtx.createBufferSource();rainNode.buffer=buffer;rainNode.loop=true;const filter=audioCtx.createBiquadFilter();filter.type='lowpass';filter.frequency.value=900;const gain=audioCtx.createGain();gain.gain.value=.08;rainNode.connect(filter).connect(gain).connect(audioCtx.destination);rainNode.start()}else if(rainNode){rainNode.stop();rainNode=null}}
function cinematicTone(){if(!audioCtx)return;const now=audioCtx.currentTime;[98,147,220,294].forEach((frequency,i)=>{const oscillator=audioCtx.createOscillator(),gain=audioCtx.createGain();oscillator.type=i<2?'sine':'triangle';oscillator.frequency.setValueAtTime(frequency,now+i*.55);gain.gain.setValueAtTime(.0001,now+i*.55);gain.gain.exponentialRampToValueAtTime(.075,now+i*.55+.25);gain.gain.exponentialRampToValueAtTime(.0001,now+i*.55+2.8);oscillator.connect(gain).connect(audioCtx.destination);oscillator.start(now+i*.55);oscillator.stop(now+i*.55+3)})}
let introStarted=false,introTimer;function finishIntro(){clearTimeout(introTimer);const rain=$('#rainSound');if(rain){rain.pause();rain.currentTime=0}$('#intro').classList.add('is-leaving');$('#site').hidden=false;setTimeout(()=>$('#intro')?.remove(),1100)}
function startIntro(){if(introStarted)return;introStarted=true;$('#skipCinematic').hidden=false;const rain=$('#rainSound');rain.volume=.42;rain.play().catch(()=>ambient(true));setTimeout(()=>$('#intro')?.classList.add('clouds-arrive'),180);setTimeout(()=>$('#intro')?.classList.add('storm-active'),900);setTimeout(()=>$('#intro')?.classList.add('golden-ray'),2200);setTimeout(()=>{const impact=$('#logoImpactSound');impact.volume=.82;impact.play().catch(()=>{});$('#intro')?.classList.add('logo-reveal','notes-reveal');setTimeout(()=>$('#stationIdent')?.play().catch(()=>{}),420)},3650);introTimer=setTimeout(finishIntro,13500)}
[$('#soundToggle'),$('#soundToggleHeader')].forEach(b=>b&&b.addEventListener('click',()=>{ambient(!soundOn);if(soundOn)cinematicTone()}));$('#enterButton').addEventListener('click',startIntro);$('#skipCinematic').addEventListener('click',finishIntro);requestAnimationFrame(()=>requestAnimationFrame(startIntro));
const drawer=$('#drawer'),scrim=$('#scrim');function closeMenu(){drawer.classList.remove('open');scrim.classList.remove('open');drawer.setAttribute('aria-hidden','true');$('#menuButton').setAttribute('aria-expanded','false')}$('#menuButton').onclick=()=>{drawer.classList.add('open');scrim.classList.add('open');drawer.setAttribute('aria-hidden','false');$('#menuButton').setAttribute('aria-expanded','true')};$('#closeMenu').onclick=closeMenu;scrim.onclick=closeMenu;$('#drawerNav').onclick=e=>{if(e.target.closest('a'))closeMenu()};
$$('.tab').forEach(t=>t.onclick=()=>{$$('.tab').forEach(x=>x.classList.remove('active'));$$('.tab-panel').forEach(x=>x.classList.remove('active'));t.classList.add('active');const panel=$('#'+t.dataset.panel);panel.classList.add('active');panel.style.animation='none';requestAnimationFrame(()=>panel.style.animation='')});
const sermons={sermon1:'<h3>Fe en medio de la prueba</h3><p>La fe no niega la dificultad; decide mirar más alto que la dificultad. Ora, recuerda las promesas de Dios y da hoy el próximo paso posible.</p>',sermon2:'<h3>La paz que guarda el corazón</h3><p>La paz de Dios no siempre cambia primero el escenario; muchas veces cambia primero nuestro interior para que podamos atravesarlo.</p>',sermon3:'<h3>Comenzar de nuevo</h3><p>Tu pasado no tiene la última palabra. Dios puede restaurar, redirigir y abrir una nueva etapa con propósito.</p>'};$$('.inline-open').forEach(b=>b.onclick=()=>{const v=$('#inlineViewer');v.innerHTML=sermons[b.dataset.content];v.hidden=false;v.scrollIntoView({behavior:'smooth',block:'center'})});
const radio=$('#radioAudio');radio.src=cfg.radioStreamUrl||'';$('#playButton').onclick=async()=>{if(!radio.src){$('#nowPlaying').textContent='Agrega la URL de ZaraRadio/stream en config.js';return}try{if(radio.paused){await radio.play();$('#playButton').textContent='❚❚'}else{radio.pause();$('#playButton').textContent='▶'}}catch(e){$('#nowPlaying').textContent='No se pudo iniciar el stream. Verifica la URL HTTPS.'}};$('#volume').oninput=e=>radio.volume=Number(e.target.value);
const testimonios=['“Durante una temporada difícil, la oración del día me recordó que no estaba solo. Volví a confiar y encontré fuerzas para continuar.”','“Mi familia comenzó a escuchar la radio durante las mañanas. La música y los mensajes trajeron paz a nuestro hogar.”','“Después de mucho tiempo alejado, un devocional me motivó a volver a orar. Fue el comienzo de una nueva etapa en mi vida.”','“Aprendí que perdonar no cambia el pasado, pero sí libera el corazón. Dios restauró mi relación con una persona muy importante.”','“En medio de una enfermedad, los versículos y las oraciones de esta plataforma me ayudaron a mantener la esperanza.”'];let ti=0;$('#nextTestimonial').onclick=()=>{$('#testimonialText').textContent=testimonios[++ti%testimonios.length]};

$$('.media-choice').forEach(button=>button.addEventListener('click',()=>{$$('.media-choice').forEach(x=>x.classList.remove('active'));$$('.media-panel').forEach(x=>x.classList.remove('active'));button.classList.add('active');$('#'+button.dataset.mediaPanel).classList.add('active');$('.media-hub').classList.remove('cinema-playing');$('.media-hub').classList.add('cinema-lit')}));
$$('.wallpaper-card').forEach(b=>b.onclick=()=>{const v=$('#wallpaperViewer'),img=v.querySelector('img'),a=v.querySelector('a');img.src=b.dataset.image;a.href=b.dataset.image;v.hidden=false;requestAnimationFrame(()=>v.classList.add('phone-active'));v.scrollIntoView({behavior:'smooth',block:'center'})});
$('#videoLink').addEventListener('click',e=>{const href=e.currentTarget.href;if(href.endsWith('#'))return;e.preventDefault();const hub=$('.media-hub');hub.classList.remove('cinema-lit');hub.classList.add('cinema-playing');if(!audioCtx)audioCtx=new (window.AudioContext||window.webkitAudioContext)();if(audioCtx.state==='suspended')audioCtx.resume();cinematicTone();setTimeout(()=>location.href=href,1800)});
const sceneObserver=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting)entry.target.classList.add('scene-active')}),{threshold:.23});$$('.content-section,#radio').forEach(section=>sceneObserver.observe(section));
$$('[data-donation]').forEach(b=>b.onclick=()=>{const k=b.dataset.donation,u=cfg.donations?.[k],r=$('#donationResult');r.hidden=false;r.innerHTML=u?`<p>Serás dirigido al método seleccionado.</p><a class="inline-open" href="${u}" target="_blank" rel="noopener">Continuar de forma segura</a>`:'<p>Este método todavía no está configurado. Añade el enlace privado correspondiente en <code>config.js</code>.</p>'});
$('#prayerForm').onsubmit=async e=>{e.preventDefault();const s=$('#formStatus');s.textContent='Enviando…';try{const r=await fetch('/api/prayer',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(Object.fromEntries(new FormData(e.target)))});if(!r.ok)throw Error();s.textContent='Petición recibida. Estaremos orando contigo.';e.target.reset()}catch{s.textContent='La función está en modo demostración. Conectaremos el almacenamiento seguro en el panel administrativo.'}};
$('#videoLink').href=cfg.videoChannelUrl||'#';$('#socialLink').href=cfg.socialUrl||'#';
let deferredPrompt;window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;$('#installButton').hidden=false});$('#installButton').onclick=async()=>{if(deferredPrompt){deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null}};
let clicks=0,timer;$('#adminTrigger').onclick=()=>{clicks++;clearTimeout(timer);timer=setTimeout(()=>clicks=0,1800);if(clicks>=5)location.href='/admin/'};
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('/sw.js'));
